import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "www.insightwithin.com" },
      { protocol: "https", hostname: "tiimg.tistatic.com" },
      { protocol: "https", hostname: "cpimg.tistatic.com" },
      { protocol: "https", hostname: "encrypted-tbn0.gstatic.com" },
      { protocol: "https", hostname: "dn-24.com" },
      { protocol: "https", hostname: "cdn2.bigcommerce.com" },
      { protocol: "https", hostname: "supraprint.pl" },
      { protocol: "https", hostname: "5.imimg.com" },
      { protocol: "https", hostname: "framerusercontent.com" },
      { protocol: "https", hostname: "images.unsplash.com" },
      { protocol: "https", hostname: "pbs.twimg.com" },
      { protocol: "https", hostname: "d91ztqmtx7u1k.cloudfront.net" },
      { protocol: "https", hostname: "i.pinimg.com" },
      { protocol: "https", hostname: "ssbspl.com" },
      { protocol: "https", hostname: "amazingsign.co.in" },
      { protocol: "https", hostname: "weetect.com" },
      { protocol: "https", hostname: "www.weetect.com" },
      { protocol: "https", hostname: "static.vecteezy.com" },
      { protocol: "https", hostname: "3.imimg.com" },
      { protocol: "https", hostname: "i.ytimg.com" },
      { protocol: "https", hostname: "img500.exportersindia.com" },
      { protocol: "https", hostname: "i.ebayimg.com" },
      { protocol: "https", hostname: "www.simco-ion.es" },
      { protocol: "https", hostname: "lh3.googleusercontent.com" },
      { protocol: "https", hostname: "images.jdmagicbox.com" },
      { protocol: "https", hostname: "sc04.alicdn.com" },
      { protocol: "https", hostname: "anuprerna-bloomscorp.s3.ap-south-1.amazonaws.com" },
      { protocol: "https", hostname: "content.jdmagicbox.com" },
      { protocol: "https", hostname: "imprintbd.com" },
      { protocol: "https", hostname: "londonmetalstore.co.uk" },
      { protocol: "https", hostname: "foun10.in" },
      { protocol: "https", hostname: "www.makeneon.com" },
      { protocol: "https", hostname: "m.media-amazon.com" },
      { protocol: "https", hostname: "www.shutterstock.com" },
      { protocol: "https", hostname: "content.jdmagicbox.com" },
      { protocol: "https", hostname: "d91ztqmtx7u1k.cloudfront.net" },
      { protocol: "https", hostname: "cdn.shopify.com" },
      { protocol: "https", hostname: "encrypted-tbn0.gstatic.com" },
      { protocol: "https", hostname: "www.e-arc.in" },
      { protocol: "https", hostname: "www.crealityfalcon.com" },
      { protocol: "https", hostname: "archidplydecor.com" },
      { protocol: "https", hostname: "images.jdmagicbox.com" },
      { protocol: "https", hostname: "cpimg.tistatic.com" },
      { protocol: "https", hostname: "www.crealityfalcon.com" },
      { protocol: "https", hostname: "blog-aludecor.s3.ap-south-1.amazonaws.com" },
      { protocol: "https", hostname: "image.made-in-china.com" },
      { protocol: "https", hostname: "alstoneindia.com" },
      { protocol: "https", hostname: "cdn.prod.website-files.com" },
      { protocol: "https", hostname: "thumbs.dreamstime.com" },
    



    ],
  },
  turbopack: {
    root: "E:\\mn-graphic-signage\\mn-graphics",
  },
};
export default nextConfig;
